services:
    neurolens-backend:
        build:
            context: ./backend
            dockerfile: ../Dockerfile.backend
        container_name: neurolens-backend
        restart: unless-stopped
        ports:
            - "8080:8080"
        env_file:
            - .env